# Generated by Django 2.2.5 on 2020-08-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description_html',
        ),
    ]
